name: test
description: "A test stack"
repos:
  - github.com/bozemanpass/stack-test-project@test-branch
containers:
  - name: bozemanpass/test-container
  # Note: the ref (repo) and path (within the repo) are inferred because we use standard naming conventions in this repo
pods:
  - test
