version: "1.0"
name: external-test
description: "An external test stack"
repos:
  - github.com/bozemanpass/stack-test-project@test-branch
containers:
  - bpi/external-test-container
pods:
  - external-test
