services:

  database:
    image: bozemanpass/test-database-container:stack
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "test-user"
      POSTGRES_DB: "test-db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432"

  test-client:
    image: bozemanpass/test-database-client:stack

volumes:
  db-data:
